/** Local capability-PDF photo galleries (JPEG/PNG only for @react-pdf). */
export const subsectorGalleries: Record<string, string[]> = {
  "airports": ["/assets/subsectors/airports/1.jpg", "/assets/subsectors/airports/2.jpg", "/assets/subsectors/airports/3.jpg"],
  "apartments": ["/assets/subsectors/apartments/1.jpg", "/assets/subsectors/apartments/2.jpg", "/assets/subsectors/apartments/3.jpg", "/assets/subsectors/apartments/4.jpg", "/assets/subsectors/apartments/5.jpg", "/assets/subsectors/apartments/6.jpg", "/assets/subsectors/apartments/7.jpg", "/assets/subsectors/apartments/8.jpg", "/assets/subsectors/apartments/9.jpg"],
  "assisted-living": ["/assets/subsectors/assisted-living/1.jpg", "/assets/subsectors/assisted-living/2.jpg", "/assets/subsectors/assisted-living/3.jpg", "/assets/subsectors/assisted-living/4.jpg"],
  "bars": ["/assets/subsectors/bars/1.jpg", "/assets/subsectors/bars/2.jpg", "/assets/subsectors/bars/3.jpg"],
  "cafes": ["/assets/subsectors/cafes/1.jpg", "/assets/subsectors/cafes/2.jpg", "/assets/subsectors/cafes/3.jpg", "/assets/subsectors/cafes/4.jpg", "/assets/subsectors/cafes/5.jpg", "/assets/subsectors/cafes/6.jpg", "/assets/subsectors/cafes/7.jpg", "/assets/subsectors/cafes/8.jpg"],
  "civic-buildings": ["/assets/subsectors/civic-buildings/1.jpg", "/assets/subsectors/civic-buildings/2.jpg", "/assets/subsectors/civic-buildings/3.jpg"],
  "colleges": ["/assets/subsectors/colleges/1.jpg", "/assets/subsectors/colleges/2.jpg", "/assets/subsectors/colleges/3.jpg", "/assets/subsectors/colleges/4.jpg", "/assets/subsectors/colleges/5.jpg", "/assets/subsectors/colleges/6.jpg"],
  "commercial-interiors": ["/assets/subsectors/commercial-interiors/1.jpg", "/assets/subsectors/commercial-interiors/2.jpg", "/assets/subsectors/commercial-interiors/3.jpg"],
  "community-centres": ["/assets/subsectors/community-centres/1.jpg", "/assets/subsectors/community-centres/2.jpg", "/assets/subsectors/community-centres/3.jpg"],
  "condominiums": ["/assets/subsectors/condominiums/1.jpg", "/assets/subsectors/condominiums/2.jpg", "/assets/subsectors/condominiums/3.jpg", "/assets/subsectors/condominiums/4.jpg"],
  "convenience-stores": ["/assets/subsectors/convenience-stores/1.jpg", "/assets/subsectors/convenience-stores/2.jpg", "/assets/subsectors/convenience-stores/3.jpg"],
  "corporate-offices": ["/assets/subsectors/corporate-offices/1.jpg", "/assets/subsectors/corporate-offices/2.jpg", "/assets/subsectors/corporate-offices/3.jpg"],
  "cultural-centres": ["/assets/subsectors/cultural-centres/1.jpg", "/assets/subsectors/cultural-centres/2.jpg", "/assets/subsectors/cultural-centres/3.jpg"],
  "custom-architectural-millwork": ["/assets/subsectors/custom-architectural-millwork/1.jpg", "/assets/subsectors/custom-architectural-millwork/2.jpg", "/assets/subsectors/custom-architectural-millwork/3.jpg"],
  "daycares": ["/assets/subsectors/daycares/1.jpg", "/assets/subsectors/daycares/2.jpg", "/assets/subsectors/daycares/3.jpg"],
  "entertainment-venues": ["/assets/subsectors/entertainment-venues/1.jpg", "/assets/subsectors/entertainment-venues/2.jpg", "/assets/subsectors/entertainment-venues/3.jpg", "/assets/subsectors/entertainment-venues/4.jpg", "/assets/subsectors/entertainment-venues/5.jpg", "/assets/subsectors/entertainment-venues/6.jpg", "/assets/subsectors/entertainment-venues/7.jpg"],
  "financial-institutions": ["/assets/subsectors/financial-institutions/1.jpg", "/assets/subsectors/financial-institutions/2.jpg", "/assets/subsectors/financial-institutions/3.jpg", "/assets/subsectors/financial-institutions/4.jpg"],
  "government-offices": ["/assets/subsectors/government-offices/1.jpg", "/assets/subsectors/government-offices/2.jpg", "/assets/subsectors/government-offices/3.jpg"],
  "grocery": ["/assets/subsectors/grocery/1.jpg", "/assets/subsectors/grocery/2.jpg", "/assets/subsectors/grocery/3.jpg", "/assets/subsectors/grocery/4.jpg", "/assets/subsectors/grocery/5.jpg", "/assets/subsectors/grocery/6.jpg"],
  "hospitals": ["/assets/subsectors/hospitals/1.jpg", "/assets/subsectors/hospitals/2.jpg", "/assets/subsectors/hospitals/3.jpg", "/assets/subsectors/hospitals/4.jpg"],
  "hotels": ["/assets/subsectors/hotels/1.jpg", "/assets/subsectors/hotels/2.jpg", "/assets/subsectors/hotels/3.jpg", "/assets/subsectors/hotels/4.jpg", "/assets/subsectors/hotels/5.jpg", "/assets/subsectors/hotels/6.jpg"],
  "laboratories": ["/assets/subsectors/laboratories/1.jpg", "/assets/subsectors/laboratories/2.jpg", "/assets/subsectors/laboratories/3.jpg", "/assets/subsectors/laboratories/4.jpg"],
  "learning-centres": ["/assets/subsectors/learning-centres/1.jpg", "/assets/subsectors/learning-centres/2.jpg", "/assets/subsectors/learning-centres/3.jpg"],
  "libraries": ["/assets/subsectors/libraries/1.jpg", "/assets/subsectors/libraries/2.jpg", "/assets/subsectors/libraries/3.jpg"],
  "long-term-care": ["/assets/subsectors/long-term-care/1.jpg", "/assets/subsectors/long-term-care/2.jpg", "/assets/subsectors/long-term-care/3.jpg", "/assets/subsectors/long-term-care/4.jpg"],
  "luxury-residential-common-areas": ["/assets/subsectors/luxury-residential-common-areas/1.jpg", "/assets/subsectors/luxury-residential-common-areas/2.jpg", "/assets/subsectors/luxury-residential-common-areas/3.jpg", "/assets/subsectors/luxury-residential-common-areas/4.jpg"],
  "luxury-retail": ["/assets/subsectors/luxury-retail/1.jpg", "/assets/subsectors/luxury-retail/2.jpg", "/assets/subsectors/luxury-retail/3.jpg"],
  "manufacturing-facilities": ["/assets/subsectors/manufacturing-facilities/1.jpg", "/assets/subsectors/manufacturing-facilities/2.jpg", "/assets/subsectors/manufacturing-facilities/3.jpg"],
  "medical-clinics": ["/assets/subsectors/medical-clinics/1.jpg", "/assets/subsectors/medical-clinics/2.jpg", "/assets/subsectors/medical-clinics/3.jpg", "/assets/subsectors/medical-clinics/4.jpg"],
  "multi-residential": ["/assets/subsectors/multi-residential/1.jpg", "/assets/subsectors/multi-residential/2.jpg", "/assets/subsectors/multi-residential/3.jpg"],
  "museums": ["/assets/subsectors/museums/1.jpg", "/assets/subsectors/museums/2.jpg", "/assets/subsectors/museums/3.jpg"],
  "pharmacies": ["/assets/subsectors/pharmacies/1.jpg", "/assets/subsectors/pharmacies/2.jpg", "/assets/subsectors/pharmacies/3.jpg"],
  "professional-offices": ["/assets/subsectors/professional-offices/1.jpg", "/assets/subsectors/professional-offices/2.jpg", "/assets/subsectors/professional-offices/3.jpg"],
  "public-libraries": ["/assets/subsectors/public-libraries/1.jpg", "/assets/subsectors/public-libraries/2.jpg", "/assets/subsectors/public-libraries/3.jpg"],
  "quick-service-restaurants": ["/assets/subsectors/quick-service-restaurants/1.jpg", "/assets/subsectors/quick-service-restaurants/2.jpg", "/assets/subsectors/quick-service-restaurants/3.jpg", "/assets/subsectors/quick-service-restaurants/4.jpg", "/assets/subsectors/quick-service-restaurants/5.jpg", "/assets/subsectors/quick-service-restaurants/6.jpg"],
  "recreation-centres": ["/assets/subsectors/recreation-centres/1.jpg", "/assets/subsectors/recreation-centres/2.jpg", "/assets/subsectors/recreation-centres/3.jpg"],
  "religious-buildings": ["/assets/subsectors/religious-buildings/1.jpg", "/assets/subsectors/religious-buildings/2.jpg", "/assets/subsectors/religious-buildings/3.jpg"],
  "resorts": ["/assets/subsectors/resorts/1.jpg", "/assets/subsectors/resorts/2.jpg", "/assets/subsectors/resorts/3.jpg", "/assets/subsectors/resorts/4.jpg", "/assets/subsectors/resorts/5.jpg", "/assets/subsectors/resorts/6.jpg"],
  "restaurants": ["/assets/subsectors/restaurants/1.jpg", "/assets/subsectors/restaurants/2.jpg", "/assets/subsectors/restaurants/3.jpg", "/assets/subsectors/restaurants/4.jpg", "/assets/subsectors/restaurants/5.jpg", "/assets/subsectors/restaurants/6.jpg", "/assets/subsectors/restaurants/7.jpg"],
  "retail-stores": ["/assets/subsectors/retail-stores/1.jpg", "/assets/subsectors/retail-stores/2.jpg", "/assets/subsectors/retail-stores/3.jpg"],
  "retirement-communities": ["/assets/subsectors/retirement-communities/1.jpg", "/assets/subsectors/retirement-communities/2.jpg", "/assets/subsectors/retirement-communities/3.jpg", "/assets/subsectors/retirement-communities/4.jpg"],
  "schools": ["/assets/subsectors/schools/1.jpg", "/assets/subsectors/schools/2.jpg", "/assets/subsectors/schools/3.jpg", "/assets/subsectors/schools/4.jpg"],
  "senior-living": ["/assets/subsectors/senior-living/1.jpg", "/assets/subsectors/senior-living/2.jpg", "/assets/subsectors/senior-living/3.jpg", "/assets/subsectors/senior-living/4.jpg"],
  "shopping-centres": ["/assets/subsectors/shopping-centres/1.jpg", "/assets/subsectors/shopping-centres/2.jpg", "/assets/subsectors/shopping-centres/3.jpg"],
  "showrooms": ["/assets/subsectors/showrooms/1.jpg", "/assets/subsectors/showrooms/2.jpg", "/assets/subsectors/showrooms/3.jpg"],
  "special-projects": ["/assets/subsectors/special-projects/1.jpg", "/assets/subsectors/special-projects/2.jpg", "/assets/subsectors/special-projects/3.jpg"],
  "student-housing": ["/assets/subsectors/student-housing/1.jpg", "/assets/subsectors/student-housing/2.jpg", "/assets/subsectors/student-housing/3.jpg", "/assets/subsectors/student-housing/4.jpg"],
  "training-facilities": ["/assets/subsectors/training-facilities/1.jpg", "/assets/subsectors/training-facilities/2.jpg", "/assets/subsectors/training-facilities/3.jpg"],
  "transit": ["/assets/subsectors/transit/1.jpg", "/assets/subsectors/transit/2.jpg", "/assets/subsectors/transit/3.jpg"],
  "universities": ["/assets/subsectors/universities/1.jpg", "/assets/subsectors/universities/2.jpg", "/assets/subsectors/universities/3.jpg", "/assets/subsectors/universities/4.jpg", "/assets/subsectors/universities/5.jpg"],
  "ymca": ["/assets/subsectors/ymca/1.jpg", "/assets/subsectors/ymca/2.jpg", "/assets/subsectors/ymca/3.jpg"],
};

export function getSubsectorGallery(slug: string): string[] {
  return subsectorGalleries[slug] ?? [];
}
